<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\CulinaryBlog.Domain\CulinaryBlog.Domain.csproj" />
    <ProjectReference Include="..\..\src\CulinaryBlog.Application\CulinaryBlog.Application.csproj" />
    <ProjectReference Include="..\..\src\CulinaryBlog.Infrastructure\CulinaryBlog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\CulinaryBlog.API\CulinaryBlog.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

</Project>
